name = "GameUI"
uuid = "a4582ee1-eb5d-430c-be92-f21ddeb7e6c7"
authors = ["Michael Daub <mwdaub@gmail.com>"]
version = "0.1.0"

[deps]
CSFML = "538df835-4bef-5bfa-b281-4025a4f7e8ff"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
